package com.llk.schedular;

public class Constants {
	public static final String SQL_EMAIL_NOTIFICATIONS = "SELECT CLIENT_ID,THERAPIST_ID,CLIENT_NAME,THERAPIST_NAME,CLIENT_EMAIL,THERAPIST_EMAIL,THERAPY_NAME,THERAPY_ID FROM MASTER_SCHEDULES_ALL_VIEW WHERE (CLIENT_COMM_MODE='EMAIL' OR CLIENT_COMM_MODE1='EMAIL')";
	public static final String SQL_SMS_NOTIFICATIONS = "SELECT CLIENT_ID,THERAPIST_ID,CLIENT_NAME,THERAPIST_NAME,CLIENT_PHONE,THERAPIST_PHONE,THERAPY_NAME,THERAPY_ID FROM MASTER_SCHEDULES_ALL_VIEW WHERE (CLIENT_COMM_MODE='SMS' OR CLIENT_COMM_MODE1='SMS')";	
}
