package com.llk.client.util;

public class Constants {
	private Constants() {};
	public static final String API_VERSION="/api/v1";	
	public static final String IMG_UPLOAD_PATH="/profile/image/";
	public static final String MSG_CLIENT_DELETE_SUCCESS="Client Successfully deleted.";
	public static final String MSG_CLIENT_DELETE_FAILURE="Unable to delete client.";
	public static final String SUCCESS="Success";
	public static final String FAILURE="Failure";
	public static final String DATE_FORMAT=com.llk.common.util.Constants.DATE_FORMAT;
	public static final String TIME_FORMAT=com.llk.common.util.Constants.TIME_FORMAT;
	public static final String PROFILE_DEV="dev";
	
	public static final String URL_SAVE_CLIENT = "/save";
	public static final String URL_DELETE_CLIENT="/delete/{clientId}";
	public static final String URL_SEARCH_CLIENTS="/search";
	public static final String URL_DETAIL_CLIENT="/detail/{clientId}";
	public static final String URL_UPDATE_CLIENT="/update";
	public static final String URL_CLIENTS_ALL="/all";
	public static final String URL_SAVE_CLIENT_SCHEDULE="/saveschedule";
	public static final String URL_CANCEL_CLIENT_SCHEDULE="/cancelschedule";
	public static final String URL_CLIENT_SCHEDULE_EVENTS="/clientschedules";
	public static final String URL_CLIENT_UNSUBSCRIBE="/unsubscribe/{clientId}";
	public static final String URL_COMMUNICATION_MODES="/communicationmodes";
	public static final String URL_THERAPY_TYPES="/therapytypes";
	public static final String URL_CLIENT_DETAILS = "/detail/{therapistId}";
	public static final String URL_LOV="/lov/{type}";
	
	
	public static final String SQL_COMMUNICATION_MODES = "select communication_mode_id as value,mode_name as display from COMMUNICATION_MODES";
	public static final String SQL_THERAPY_TYPES = "select THERAPY_ID as value,THERAPY_NAME as display from THERAPY_TYPES";
	public static final String SQL_SAVE_PARTY="INSERT INTO PARTY(FIRST_NAME,LAST_NAME,EMAIL,PHONE,GENDER,DOB,PROFILE_IMG_URL) VALUES(:FIRST_NAME,:LAST_NAME,:EMAIL,:PHONE,:GENDER,:DOB,:PROFILE_IMG_URL)";
	public static final String SQL_SAVE_CLIENT="INSERT INTO CLIENT(PARTY_ID,COMMUNICATION_MODE,GUARDIAN_NAME,GUARDIAN_RELATION,CLASSES,STATUS,INSURANCE_DETAILS,SEND_NOTIFICATION,ATTRIBUTE2,ATTRIBUTE1) VALUES(:PARTY_ID,:COMMUNICATION_MODE,:GUARDIAN_NAME,:GUARDIAN_RELATION,:CLASSES,:STATUS,:INSURANCE_DETAILS,:SEND_NOTIFICATION,:ATTRIBUTE2,:ATTRIBUTE1)";
	public static final String SQL_SEARCH_CLIENT="select distinct client_id,first_name ,last_name,phone,gender,email,GUARDIAN_NAME,GUARDIAN_RELATION,profile_img_url from CLIENTS_ALL_VIEW where 1=1";
	public static final String SQL_SAVE_CLIENT_AVAILABILITY="INSERT INTO CLIENT_AVAILABILITY(CLIENT_ID,THERAPIST_ID,THERAPY_ID,START_DATE,END_DATE,START_TIME,END_TIME,STATUS) VALUES(:CLIENT_ID,:THERAPIST_ID,:THERAPY_ID,:START_DATE,:END_DATE,:START_TIME,:END_TIME,:STATUS)";
	public static final String SQL_SAVE_CLIENT_AVAILABILITY_OCCURENCE="INSERT INTO CLIENT_AVAILABILITY_OCCURENCES(AVAILABILITY_ID,FREQUENCE_TYPE,FREQUENCY_REPEATS,WEEK_DAYAS,END_DATE,DAY_NO,WEEK_OF_MONTH,MONTH_OF_YEAR,STATUS) VALUES(:AVAILABILITY_ID,:FREQUENCE_TYPE,:FREQUENCY_REPEATS,:WEEK_DAYAS,:END_DATE,:DAY_NO,:WEEK_OF_MONTH,:MONTH_OF_YEAR,:STATUS)";
	public static final String SQL_DELETE_CLIENT="UPDATE CLIENT SET STATUS='INACTIVE' where CLIENT_ID=:CLIENT_ID";	
	public static final String SQL_CLIENTS_ALL="SELECT DISTINCT CLIENT_ID ,NAME FROM CLIENTS_ALL_VIEW";
	public static final String SQL_PARTY_ID="SELECT PARTY_ID FROM CLIENT WHERE CLIENT_ID=:CLIENT_ID";
	public static final String SQL_UPDATE_PARTY="UPDATE PARTY SET FIRST_NAME=:FIRST_NAME,LAST_NAME=:LAST_NAME,PHONE=:PHONE,EMAIL=:EMAIL,GENDER=:GENDER,DOB=:DOB WHERE PARTY_ID=:PARTY_ID";
	public static final String SQL_UPDATE_CLIENT="UPDATE CLIENT SET COMMUNICATION_MODE=:COMMUNICATION_MODE,GUARDIAN_NAME=:GUARDIAN_NAME,GUARDIAN_RELATION=:GUARDIAN_RELATION,CLASSES=:CLASSES, INSURANCE_DETAILS=:INSURANCE_DETAILS, ATTRIBUTE2=:ATTRIBUTE2,ATTRIBUTE1=:ATTRIBUTE1 WHERE CLIENT_ID=:CLIENT_ID";
	public static final String SQL_SAVE_SCHEDULE="INSERT INTO CLIENT_SCHEDULES(CLIENT_ID,THERAPIST_ID,SCHEDULE_ID,THERAPY_ID,START_DATE,END_DATE,START_TIME,END_TIME,STATUS) VALUES(:CLIENT_ID,:THERAPIST_ID,:SCHEDULE_ID,:THERAPY_ID,:START_DATE,:END_DATE,:START_TIME,:END_TIME,:STATUS)";
	public static final String SQL_CLIENT_EVENTS="SELECT THERAPIST_ID,THERAPIST_NAME,THERAPY_ID,THERAPIST_SCHEDULE_ID,THERAPY_NAME,CLIENT_ID,CLIENT_SCHEDULE_ID,CLIENT_NAME,CLIENT_EMAIL,START_DATE,START_TIME,END_DATE,END_TIME,STATUS FROM MASTER_SCHEDULES_ALL_VIEW WHERE 1=1";
	public static final String SQL_CLIENT_DETAILS="SELECT DISTINCT FIRST_NAME,LAST_NAME,EMAIL,PHONE,DOB,client_id,PROFILE_IMG_URL,classes,GUARDIAN_NAME,GUARDIAN_RELATION,INSURANCE_DETAILS,GENDER,ATTRIBUTE2,ATTRIBUTE1,COMMUNICATION_MODE from CLIENTS_ALL_VIEW WHERE CLIENT_ID=:CLIENT_ID";
	public static final String SQL_CLIENT_COMM_UNSUBSCRIBE="UPDATE CLIENT SET SEND_NOTIFICATION='N' WHERE CLIENT_ID=:CLIENT_ID";
	public static final String SQL_LOV="SELECT MEANING as value,DESCRIPTION as display from LLK_LOOKUP_VALUES where LOOKUP_TYPE=:LOOKUP_TYPE";
	public static final String SQL_SAVE_ADDRESS="INSERT INTO PARTY_SITES(PARTY_ID,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRY,ZIP,USE_TYPE,CELL_PHONE,HOME_PHONE,WORK_PHONE,ATTRIBUTE1) VALUES(:PARTY_ID,:ADDRESS1,:ADDRESS2,:ADDRESS3,:CITY,:STATE,:COUNTRY,:ZIP,:USE_TYPE,:CELL_PHONE,:HOME_PHONE,:WORK_PHONE,:ATTRIBUTE1)";
	public static final String SQL_GET_ADDRESS="SELECT SITE_ID,ADDRESS1,ADDRESS2,CITY,STATE,COUNTRY,ZIP,USE_TYPE,CELL_PHONE,HOME_PHONE,WORK_PHONE,ATTRIBUTE1 FROM PARTY_SITES WHERE PARTY_ID=:PARTY_ID";
	public static final String SQL_UPDATE_ADDRESS="UPDATE PARTY_SITES SET ADDRESS1=:ADDRESS1,ADDRESS2=:ADDRESS2,CITY=:CITY,STATE=:STATE,COUNTRY=:COUNTRY,ZIP=:ZIP,USE_TYPE=:USE_TYPE,CELL_PHONE=:CELL_PHONE,HOME_PHONE=:HOME_PHONE,WORK_PHONE=:WORK_PHONE,ATTRIBUTE1=:ATTRIBUTE1 WHERE SITE_ID=:SITE_ID";
	public static final String SQL_CANCEL_SCHEDULE="UPDATE CLIENT_SCHEDULES SET STATUS=:STATUS WHERE 1=1";
	public static final String SQL_UPDATE_THERAPIST_SCHEDULE_STATUS="UPDATE THERAPIST_SCHEDULES SET STATUS=:STATUS WHERE SCHEDULE_ID IN(:SCHEDULE_ID)";
	public static final String SQL_THERAPIST_SCHEDULES_ID_ALL="select schedule_id from CLIENT_SCHEDULES where CLIENT_ID=:CLIENT_ID";
	
	

}
