SET SQL_SAFE_UPDATES=0;
delete from ROLES_RES_MAPPING ;
delete from RESPONSABILITIES;
delete from ROLES;
delete from THERAPY_TYPES;
delete from THERAPIST_LEVEL;

ALTER TABLE LLK_LOOKUP_VALUES  ADD CONSTRAINT  UC_LOOKUP_VALUES UNIQUE (LOOKUP_TYPE, LOOKUP_CODE, MEANING);

ALTER TABLE ROLES_RES_MAPPING  ADD CONSTRAINT  UC_ROLES_RES_MAPPING UNIQUE (ROLE_ID, RES_ID);

ALTER TABLE PARTY_ROLES_MAPING  ADD CONSTRAINT  UC_ROLES_RES_MAPPING UNIQUE (PARTY_ID, ROLE_ID);

INSERT INTO COMMUNICATION_MODES(MODE_NAME) VALUES('SMS');
INSERT INTO COMMUNICATION_MODES(MODE_NAME) VALUES('EMAIL');


INSERT INTO THERAPIST_LEVEL(LEVEL_NAME) VALUES('RBT');
INSERT INTO THERAPIST_LEVEL(LEVEL_NAME) VALUES('ABA');
INSERT INTO THERAPIST_LEVEL(LEVEL_NAME) VALUES('BCBA');
INSERT INTO THERAPIST_LEVEL(LEVEL_NAME) VALUES('Part-time');


INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Speech Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Art Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Occupational Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Applied Behavior Analysis Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Music Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Recreational Therapy');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Technology');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Life Skills (Occupational Therapy)');
INSERT INTO THERAPY_TYPES(THERAPY_NAME) VALUES('Group Therapy / Social Skills');


CREATE OR REPLACE VIEW THERAPISTS_ALL_VIEW AS
select DISTINCT P.PARTY_ID,T.THERAPIST_ID,TS.THERAPY_ID,TS.SCHEDULE_ID,P.FIRST_NAME,P.LAST_NAME,
CONCAT(P.FIRST_NAME ," ",P.LAST_NAME) as NAME,T.LEVEL_ID,TL.LEVEL_NAME,
P.EMAIL,P.PHONE,P.GENDER,P.PROFILE_IMG_URL,
T.CERTIFICATAIONS,TT.THERAPY_NAME,
TS.START_DATE,TS.END_DATE,TS.START_TIME,TS.END_TIME,TS.STATUS,
P.DOB,T.COMMUNICATION_MODE,T.ATTRIBUTE1,T.STATUS AS THERAPIST_STATUS
from PARTY P,
 THERAPIST T,
 THERAPY_TYPES TT ,
 THERAPIST_SESSIONS TSE,
 THERAPIST_SCHEDULES TS, 
 THERAPIST_LEVEL TL
 WHERE P.PARTY_ID=T.PARTY_ID
 AND TSE.THERAPIST_ID=T.THERAPIST_ID
 AND TS.THERAPIST_ID = T.THERAPIST_ID 
 AND TS.THERAPY_ID = TT.THERAPY_ID
 AND T.LEVEL_ID = TL.LEVEL_ID;
 
 
CREATE OR REPLACE VIEW CLIENTS_ALL_VIEW AS
select DISTINCT C.CLIENT_ID,CAA.OCCURENCE_ID,TT.THERAPY_ID,TT.THERAPY_NAME,
P.FIRST_NAME,P.LAST_NAME,CONCAT(P.FIRST_NAME ," ",P.LAST_NAME) as NAME,P.EMAIL,P.PHONE,
P.GENDER,P.PROFILE_IMG_URL,C.GUARDIAN_NAME,C.GUARDIAN_RELATION,C.CLASSES,C.INSURANCE_DETAILS,C.SEND_NOTIFICATION,P.DOB,
CA.AVAILABILITY_ID,CA.START_DATE,CA.END_DATE,C.ATTRIBUTE2,
CA.START_TIME,CA.END_TIME,C.COMMUNICATION_MODE,C.ATTRIBUTE1
from 
 PARTY P,
 CLIENT C, 
 CLIENT_AVAILABILITY CA,
 CLIENT_AVAILABILITY_OCCURENCES CAA, 
 THERAPY_TYPES TT 
 WHERE 
 P.PARTY_ID=C.PARTY_ID   
 AND C.CLIENT_ID=CA.CLIENT_ID
 AND CA.AVAILABILITY_ID=CAA.AVAILABILITY_ID
 AND TT.THERAPY_ID = CA.THERAPY_ID
 AND C.STATUS ='ACTIVE';
 
CREATE OR REPLACE VIEW MASTER_SCHEDULES_ALL_VIEW AS 
SELECT DISTINCT CS.CLIENT_ID,CS.CLIENT_SCHEDULE_ID,CS.SCHEDULE_ID AS THERAPIST_SCHEDULE_ID,TALLV.THERAPIST_ID,
CS.START_DATE,CS.END_DATE,CS.START_TIME,CS.END_TIME,CS.STATUS,TALLV.NAME AS THERAPIST_NAME,CS.THERAPY_ID,TALLV.THERAPY_NAME,
TALLV.EMAIL AS THERAPIST_EMAIL,
TALLV.PHONE AS THERAPIST_PHONE,
TALLV.COMMUNICATION_MODE AS THERAPIST_COMM_MODE,TALLV.ATTRIBUTE1 AS  THERAPIST_COMM_MODE1,
CONCAT(P.FIRST_NAME ," ",P.LAST_NAME) AS CLIENT_NAME,P.EMAIL AS CLIENT_EMAIL,P.PHONE AS CLIENT_PHONE,
C.COMMUNICATION_MODE AS CLIENT_COMM_MODE,C.ATTRIBUTE1 AS CLIENT_COMM_MODE1,TALLV.STATUS AS THERAPIST_SC_STATUS,
CS.ATTRIBUTE1 AS OUTLOOK_EVENT_SEND,CS.ATTRIBUTE5 AS OUTLOOK_EVENT_ID
FROM PARTY P,
CLIENT C,
CLIENT_SCHEDULES CS,
THERAPISTS_ALL_VIEW TALLV
WHERE TALLV.SCHEDULE_ID=CS.SCHEDULE_ID
AND C.CLIENT_ID=CS.CLIENT_ID
AND C.PARTY_ID=P.PARTY_ID;





INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('GENDER','GENDER','M','Male');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('GENDER','GENDER','F','Female');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('GENDER','GENDER','NS','Not Specified');

INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREPEATS','REPEATS','Y','Yes');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREPEATS','REPEATS','N','No');

INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALWEEK','WEEK','1','1');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALWEEK','WEEK','2','2');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALWEEK','WEEK','3','3');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALWEEK','WEEK','4','4');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALWEEK','WEEK','5','5');


INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','5','5min');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','10','10mins');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','15','15mins');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','30','30mins');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','45','45mins');
INSERT INTO LLK_LOOKUP_VALUES(LOOKUP_TYPE,LOOKUP_CODE,MEANING,DESCRIPTION) VALUES('CALREMINDER','REMINDER','60','1hr');

 
 










